# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-slim

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Zip folders
        run: |
          cd min-ser-res/weeb-data && zip -r ../../weeb-data.zip * && cd ../..
          cd min-ser-res/weeb-res && zip -r ../../weeb-res.zip * && cd ../..

      # Runs a set of commands using the runners shell
      - name: Upload
        run: |
          gh release create ./weeb-data.zip ./weeb-res.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
